name: Update stable.json and DingTalk Notification

on:
  workflow_dispatch:

jobs:
  update_stable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List /data contents
        run: |
          echo "Listing /data:"
          ls -alh /data
